### ISSUE TITLE
promote geometry_experimental to geometry2

### ISSUE THREAD

**Issue by tfoote** [ros/geometry2#160]
We should take this opportunity to review the documentation and make sure it's at parity with geometry. Below are the tasks from my audit. 

Validate tutorials and documentation have coverage of everything in geometry.
- [x] Port tf/Overview to tf2/Overview 
  - [x] DataTypes -> [tf2 doxygen](http://docs.ros.org/jade/api/tf2/html/) + http://wiki.ros.org/tf2#Supported_Datatypes + datatype support packages documentation (see below)
  - [x] Transformations and Frames -> http://wiki.ros.org/tf2/Terminology
  - [x] Broadcasting Transforms 
    - [x] cpp Tutorials http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20broadcaster%20%28C%2B%2B%29
    - [x] python tutorials http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20broadcaster%20%28Python%29 
    - [x] overview tf2_ros code API http://docs.ros.org/jade/api/tf2_ros/html/ 
  - [x] Using published transforms
    - [x] cpp Tutorials http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20listener%20%28C%2B%2B%29
    - [x] python Tutorials http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20listener%20%28Python%29
    - [x] overview tf2_ros code API http://docs.ros.org/jade/api/tf2_ros/html/ #163
  - [x] Exceptions
    - [x] overview tf2_ros code API http://docs.ros.org/jade/api/tf2_ros/html/  #163 
- [x] Port tf/FAQ
  - [x] CommonQuestions: http://wiki.ros.org/tf2/CommonQuestions
  - [x] FAQ to answers.ros.org
  - [x] FAQ to old tf answers.ros.org tags.
- [x] Port geometry/RotationMethods
- [x] Port geometry/CoordinateFrameConventions (reference REPs 103, 105, 120, remove tf_prefix) Embedded in http://wiki.ros.org/tf2#Coordinate_Frame_Conventions
- [x] document static transform
  - [x] add tutorial @mikaelarguedas #165  [cpp](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20static%20broadcaster%20%28C%2B%2B%29) [python](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20static%20broadcaster%20%28Python%29)
  - [x] add command line tool documentation http://wiki.ros.org/tf2_ros#static_transform_publisher
- [x] Rename geometry_experimental -> geometry2 Do this last @tfoote
  - [x] create geometry2 metapackage #160
  - [x] mark geometry_experimental depending on geometry2 instead of directly on the packages. #160
- [x] Create page to describe templated convert and transform methods: 
  - [x] How to use the conversions: http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions
  - [x] Document how to add a new package implementation [c++](http://wiki.ros.org/tf2/Tutorials/Create%20Data%20Conversion%20Package%20%28C%2B%2B%29) [python](http://wiki.ros.org/tf2/Tutorials/Create%20Data%20Conversion%20Package%20%28Python%29#preview)

Fill in wiki pages for:
- [x] tf2_bullet (mostly link/include of convert documentation)
- [x] tf2_eigen (mostly link/include of convert documentation)
- [x] tf2_geometry_msgs (mostly link/include of convert documentation)
- [x] tf2_kdl (mostly link/include of convert documentation)
- [x] tf2_msgs (document as internal APIs) 
- [x] tf2_py (document as python bridge, internal API) 
- [x] tf2_ros 
- [x] tf2_sensor_msgs (mostly link/include of convert documentation)
- [x] tf2_tools
- [x] geometry2

Much of the content can be shared using includes

tf2_ros
- [x] Fill in doxygen main page for c++ giving API overview (good sources: http://wiki.ros.org/tf/Overview/Broadcasting%20Transforms http://wiki.ros.org/tf/Overview  #163/Using%20Published%20Transforms and http://wiki.ros.org/tf/Overview/Exceptions ) 
- [x] Fill in sphinx home page to give API overview  #163

Renaming
- [x] Find all references and update them to geometry2 https://github.com/ros/rosdistro/pull/10926

**Comment by jackieokay** [comment]
I can help out with this.

**Comment by tfoote** [comment]
Everything is checked off closing. Thanks for all the help @jacquelinekay @mikaelarguedas
